apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "anysource.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "anysource.backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "anysource.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "anysource.frontend.selectorLabels" . | nindent 4 }}
---
{{- if .Values.relay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sentry-relay
  labels:
    {{- include "anysource.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentry-relay
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.relay.port }}
      targetPort: {{ .Values.relay.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "anysource.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sentry-relay
{{- end }}
