{{- if .Values.telemetry.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-telemetry-completion-script
  labels:
    {{- include "anysource.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry
data:
  capture-deployment-completion.sh: |-
{{ .Files.Get "files/capture-deployment-completion.sh" | nindent 4 }}
{{- end }}
